import { appendFileSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { logsDir } from "./paths.js";

/**
 * Human-readable server log: stderr only (stdout is reserved for the MCP stdio protocol).
 */
export function logStderr(message: string): void {
  process.stderr.write(`[clonst] ${message}\n`);
}

const SAFE_NAME = /^[A-Za-z0-9._-]+$/;

/**
 * Neutralizes any path traversal in a file/directory name: characters outside
 * the whitelist become "_", "." and ".." are forbidden.
 * Sanitization (not rejection): an ugly name beats a lost LLM response.
 */
export function sanitizeName(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9._-]/g, "_");
  if (cleaned === "" || /^\.+$/.test(cleaned)) return "_";
  return cleaned;
}

function isValidSessionId(value: string): boolean {
  return SAFE_NAME.test(value) && !/^\.+$/.test(value);
}

/**
 * Logger for one review session: one JSONL line per event, plus systematic
 * saving of the complete raw CLI responses (project rule: never lose a paid
 * LLM response, even if parsing fails afterwards).
 *
 * Layout:
 *   ~/.clonst/logs/<sessionId>.jsonl
 *   ~/.clonst/logs/raw/<sessionId>/<name>.txt
 *
 * A full ping-pong lives under ONE sessionId: round 1 starts under a
 * provisional identifier then is migrated (migrateTo) to the reviewer's
 * thread_id once known; later rounds open directly under that thread_id.
 */
export class SessionLogger {
  private _sessionId: string;
  private _jsonlPath: string;
  private _rawDir: string;

  constructor(sessionId: string) {
    // The sessionId is generated by Clonst: a non-conforming name is an internal bug, throw early.
    if (!isValidSessionId(sessionId)) {
      throw new Error(`Invalid sessionId: "${sessionId}"`);
    }
    this._sessionId = sessionId;
    const dir = logsDir();
    this._jsonlPath = path.join(dir, `${sessionId}.jsonl`);
    this._rawDir = path.join(dir, "raw", sessionId);
    mkdirSync(dir, { recursive: true });
  }

  get sessionId(): string {
    return this._sessionId;
  }

  /** Path of the session's JSONL file (exposed for caller-side diagnostics). */
  get jsonlPath(): string {
    return this._jsonlPath;
  }

  /** Directory of the session's raw CLI responses (exposed for the report's audit trail). */
  get rawDir(): string {
    return this._rawDir;
  }

  /**
   * Renames the session (JSONL file + raw directory) to a new identifier,
   * typically the reviewer's thread_id once known at round 1. Never throws:
   * on failure (existing target, lock...) the session keeps its provisional
   * identifier and the failure is reported. Returns true if migration happened.
   */
  migrateTo(newSessionId: string): boolean {
    if (!isValidSessionId(newSessionId)) {
      logStderr(`session migration refused: invalid identifier "${newSessionId}"`);
      return false;
    }
    if (newSessionId === this._sessionId) return true;

    const dir = logsDir();
    const newJsonlPath = path.join(dir, `${newSessionId}.jsonl`);
    const newRawDir = path.join(dir, "raw", newSessionId);
    try {
      if (existsSync(newJsonlPath) || existsSync(newRawDir)) {
        logStderr(`session migration refused: "${newSessionId}" already exists, logs kept under "${this._sessionId}"`);
        return false;
      }
      if (existsSync(this._jsonlPath)) renameSync(this._jsonlPath, newJsonlPath);
      if (existsSync(this._rawDir)) renameSync(this._rawDir, newRawDir);
      const previous = this._sessionId;
      this._sessionId = newSessionId;
      this._jsonlPath = newJsonlPath;
      this._rawDir = newRawDir;
      this.log({ event: "session_migrated", from: previous, to: newSessionId });
      return true;
    } catch (err) {
      logStderr(`session migration failed (${err instanceof Error ? err.message : String(err)}), logs kept under "${this._sessionId}"`);
      return false;
    }
  }

  /** Appends a timestamped JSONL line. Never throws: a logging failure must not break a review. */
  log(entry: Record<string, unknown>): void {
    try {
      const line = JSON.stringify({ timestamp: new Date().toISOString(), ...entry });
      appendFileSync(this._jsonlPath, line + "\n", "utf-8");
    } catch (err) {
      logStderr(`failed to write JSONL log: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  /**
   * Path of a file inside the session's raw directory (name sanitized,
   * directory created). Used for files written directly by the CLIs
   * (--output-last-message).
   */
  rawPath(name: string): string {
    mkdirSync(this._rawDir, { recursive: true });
    return path.join(this._rawDir, sanitizeName(name));
  }

  /** Re-reads a file from the session's raw directory. null if absent or unreadable. */
  readRaw(name: string): string | null {
    try {
      return readFileSync(this.rawPath(name), "utf-8");
    } catch {
      return null;
    }
  }

  /**
   * Saves a complete raw response (CLI JSONL stdout, last message, etc.).
   * Call it BEFORE any parsing attempt. Returns the written path, or null on failure.
   */
  saveRaw(name: string, content: string): string | null {
    try {
      const filePath = this.rawPath(name);
      writeFileSync(filePath, content, "utf-8");
      return filePath;
    } catch (err) {
      logStderr(`failed to save raw response ${name}: ${err instanceof Error ? err.message : String(err)}`);
      return null;
    }
  }
}
